query($aniID: Int){
    Media (id: $aniID, type: ANIME) {
    id  
    idMal 
    mediaListEntry{
        id
        status
        progress
    }
    relations {
        edges {
        id
        relationType
        }
        #edges(relationType:\"SEQUEL\"){id}  
    } 
    title {
        romaji      
        english      
        native    
    }  
    episodes
    }
}